version: "3.9"

services:
  db:
    image: mysql
    container_name: db_distributech
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./db:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer_cnn
    restart: always
    ports:
      - ${ADMINER_PORT}:8080